### PR TITLE
Add r5py v0.0.4

### PR DESCRIPTION
**Pull request by HTenkanen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by HTenkanen** [comment]
@conda-forge-admin, please rerender

**Comment by christophfink** [comment]
We should change `recipe/meta.yaml` line 45 to   
```
license: GPL-3.0-or-later OR MIT
```

Other than that, things look fine

**Review by christophfink — CHANGES_REQUESTED** [review]
See my comment, we should change the line listing the licenses, other than that everything is ready to go.

**Review by christophfink — APPROVED** [review]
Fixed the license thingy, now ready to go :+1:

**Pull request merged**
